version: '3'

services:

  gmail-smtp-relay:
    image: namshi/smtp:latest
    restart: unless-stopped
    environment:
      GMAIL_USER: "USER@gmail.com"
      GMAIL_PASSWORD: "PASSWORD"

  netxms-agent:
    image: frostasm/netxms-nxagent:latest
    restart: unless-stopped
    volumes:
      - ./netxms-data/agent:/data
    environment:
      NETXMSD_CONFIG: "MasterServers=172.0.0.0/8"

  netxms-server:
    image: frostasm/netxms-server:latest
    restart: unless-stopped
    ports:
      - "4701:4701" # client -> server
    depends_on:
      - gmail-smtp-relay
      - netxms-agent
    volumes:
      - ./netxms-data/server:/data
    environment:
      NETXMSD_UNLOCK_ON_STARTUP: 1
      NETXMSD_UPGRADE_ON_STARTUP: 1
      NETXMSD_DEBUG_LEVEL: 0
      NETXMSD_CONFIG: ""
    command: ["/wait-for", "netxms-agent:4700", "--", "./docker-entrypoint.sh"]
    
  netxms-webui:
    image: frostasm/netxms-webui:latest
    restart: unless-stopped
    ports:
      - "8080:8080" # http://server:8080/nxmc/nxmc
    environment:
      NETXMS_SERVER: "netxms-server"
    depends_on:
      - netxms-server
