version: '3'

services:

  gmail-smtp-relay:
    image: namshi/smtp:latest
    restart: unless-stopped
    environment:
      GMAIL_USER: "USER@gmail.com"
      GMAIL_PASSWORD: "PASSWORD"

  netxms-server:
    image: frostasm/netxms-server:2.1
    restart: unless-stopped
    ports:
      - "4701:4701" # client -> server
    depends_on:
      - gmail-smtp-relay
    volumes:
      - ./netxms-server-data:/data
    environment:
      NETXMSD_UNLOCK_ON_STARTUP: 1
      NETXMSD_UPGRADE_ON_STARTUP: 1
      NETXMSD_DEBUG_LEVEL: 0
      NETXMSD_CONFIG: ""

  netxms-webui:
    image: frostasm/netxms-webui:2.1
    restart: unless-stopped
    ports:
      - "8080:8080" # http://server:8080/nxmc/nxmc
    environment:
      NETXMS_SERVER: "netxms-server"
    depends_on:
      - netxms-server